// Generated by CoffeeScript 1.3.3
(function() {
  var app, body, connect, fs, marked, views;

  connect = require('connect');

  views = require('connect-views');

  marked = require('marked');

  fs = require("fs");

  body = fs.readFileSync("views/shared/_layout.htm", "utf8");

  views.engines.marked = function() {
    return {
      contentType: 'text/html',
      render: function(str, callback) {
        var out;
        try {
          out = marked(str);
          out = body.replace("{content}", out);
        } catch (err) {
          return callback(err);
        }
        return callback(null, out);
      }
    };
  };

  views.engines.extensions['.md'] = views.engines.marked;

  app = connect().use(function(req, res, next) {
    if (req.url === "/") {
      req.url = "/posts/_index.md";
    }
    console.log(req.url);
    return next();
  }).use(connect["static"]("assets")).use(views()).listen(8080);

}).call(this);
